version: "3.8"

services:
  app:
    image: e-commerce-server:development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - db-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./.docker/data/dev/db:/var/lib/mysql
    networks:
      - db-network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
