version: "3.8"

services:
  app:
    image: e-commerce-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - db-network
    healthcheck:
      test: wget --quiet --spider --tries=1 127.0.0.1:${NODE_PORT}
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./.docker/data/prod/db:/var/lib/mysql
    networks:
      - db-network
    healthcheck:
      test: 'mysqladmin ping'
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db-network:
    driver: bridge
