version: "3.8"

services:
  app:
    image: e-commerce-server:test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=test
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - db-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: unless-stopped
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
