version: "3.8"

services:
    api:
        build:
            context: .
        image: e-commerce-api
        volumes:
            - ./:/var/www/html
        networks:
            - webserver-network
            - postgres-network
        depends_on:
            - postgres
        restart: unless-stopped

    webserver:
        image: nginx:1.21.3-alpine
        working_dir: /var/www/html
        volumes:
            - ./public:/var/www/html/public
            - ./.docker/nginx/ssl:/etc/nginx/ssl
            - ./.docker/nginx/conf:/etc/nginx/conf.d
            - ./.docker/nginx/entrypoint.sh:/docker-entrypoint.d/entrypoint.sh
        ports:
            - 8080:80
            - 443:443
        networks:
            - webserver-network
        depends_on:
            - api
        restart: unless-stopped

    postgres:
        image: postgres:14.1-alpine3.15
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./.docker/postgres/data:/var/lib/postgresql/data
        networks:
            - postgres-network
        restart: unless-stopped

    adminer:
        image: dockette/adminer:pgsql
        ports:
        - 8081:80
        networks:
            - postgres-network
        depends_on:
            - postgres
        restart: unless-stopped

networks:
    webserver-network:
    postgres-network:
