name: Test

on:
  push:
    branches: [ dev ]
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Create .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: npm install

      - name: Build docker containers
        run: docker-compose -f docker-compose.test.yml up -d --build

      - name: Wait 15 seconds
        run: sleep 15

      - name: Run Unit Test
        run: docker-compose -f docker-compose.test.yml exec -T app npm run test

  coverage-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Create .env file
        run: cp .env.example .env

      - name: Install dependencies
        run: npm install

      - name: Build docker containers
        run: docker-compose -f docker-compose.test.yml up -d --build

      - name: Wait 15 seconds
        run: sleep 15

      - name: Run Coverage Test
        run: docker-compose -f docker-compose.test.yml exec -T app npm run test --coverage
